### ISSUE TITLE
TLS 1.0/1.1 plan

### ISSUE THREAD

**Issue by JakeChampion** [jsdelivr/dns-openmix#11]
Hi,

I see you are using the [legacy TLS 1.1/1.0 and 3DES certificate from Fastly](https://github.com/jsdelivr/dns-openmix/blob/master/app.js#L7). Do you have any plans for when Fastly remove legacy TLS 1.1/1.0 and 3DES support in [June 2018](https://www.fastly.com/blog/phase-two-our-tls-10-and-11-deprecation-plan)?

**Comment by jimaek** [comment]
I will need to get in contact with them to make sure. Do you require the older TLS versions for some use-case?

**Comment by JakeChampion** [comment]
Yes, I support IE 10 and Android 4 which do not work with TLS 1.2. I was wondering if it is possible to switch provider based on TLS support using Cedexis, that could be a solution.

**Comment by jimaek** [comment]
The code runs on the DNS level so it doesn't have access to this kind of information.
We have 2 options here:
1. Work with Fastly to somehow continue the support of older TLS. I will email them today.
2. Exclude Fastly from serving to countries with high IE usage levels. Not perfect but it should solve most problems.

**Comment by jimaek** [comment]
I finally got a response from them. They said its not possible. 
I am thinking about possible solution because I know Algolia also relies on the older TLS support.

I will need to talk to them but I am thinking at best disabling Fastly for countries like India where old IE is popular and at worse removing them completely.
